repos:
- repo: local
  hooks:

  - id: black
    name: black
    stages: [pre-commit]
    language: system
    entry: hatch run black
    types: [python]

  - id: pytest
    name: pytest
    stages: [pre-commit]
    language: system
    entry: hatch run pytest
    types: [python]
    pass_filenames: false